In [3]:
import pandas as pd
import os

print("hi")

# Verzeichnis, in dem sich die CSV-Dateien befinden
verzeichnis_pfad = 'C:/Users/hendr/OneDrive - hs-bochum.de/Studium/Hochschule/Module/SS2024/BGD/data_test'

# Liste, um alle DataFrames aus den CSV-Dateien zu speichern
alle_dfs = []

hi

In [52]:
# Durch das Verzeichnis iterieren
i = 0
for datei in os.listdir(verzeichnis_pfad):
    i+=1
    if datei.endswith('.csv'):
        # Den Pfad zur aktuellen Datei erstellen
        datei_pfad = os.path.join(verzeichnis_pfad, datei)
        # CSV-Datei in ein DataFrame einlesen und zur Liste hinzufügen
        df = pd.read_csv(datei_pfad, on_bad_lines='skip', sep=';', encoding='latin-1')
        alle_dfs.append(df)
        print(i)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31

In [53]:
# Alle DataFrames in der Liste zu einer Tabelle zusammenführen
gesamt_tabelle = pd.concat(alle_dfs, ignore_index=True)

In [54]:
gesamt_tabelle.head

<bound method NDFrame.head of        01.03.2023 00:00:57;xxx.x.x.x;/vrrstd/;ID-3F98E296-19AC-495D-AFF8-BE5D9B05D1C5;0;dep;20230301;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;370.457500;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0       01.03.2023 00:01:59;xxx.x.x.x;/vrrstd/;ID-2DA2...                                                                                                                                                                                                                      \
1       01.03.2023 00:02:45;xx.xxx.xxx.xx;/nrwcibo-ios...
2       01.03.2023 00:03:01;xxx.x.x.x;/vrrstd/;ID-27E1...
3       01.03.2023 00:03:14;xx.xxx.xx.xxx;/nrwcibo-and...
4       01.03.2023 00:03:26;xxx.xxx.xx.xxx;/monitoring...
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       02.03.2023 00:00:43;xxx.x.x.x;/vrrstd/;ID-2C11A9C3-6BB5-4A83-ACA9-5D63D64ABCAB;0;dep;20230302;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;345.422400;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0                                                     NaN                                                                                                                                                                                                                      \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       03.03.2023 00:00:14;xxx.x.x.x;/vrrstd/;ID-4F78CAED-700A-48D3-BD65-358F32C40912;0;dep;20230303;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;360.683100;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0                                                     NaN                                                                                                                                                                                                                      \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       04.03.2023 00:00:49;xxx.x.x.x;/vrrstd/;ID-D13650A7-37E5-41B1-8E58-F9AA5CBAF0C5;0;dep;20230304;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;470.803300;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0                                                     NaN                                                                                                                                                                                                                      \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       05.03.2023 00:00:19;x.xx.xxx.xxx;/nrwcibo-android/;ID-E0498B0A-2F54-437B-B02E-AB1596D6B73D;0;dep;20230305;0;coord;;5314000;;RÃ¼ngsdorf (Bonn)
0                                                     NaN                                                                                             \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

        Konstantinstr. 43;stop;itp;5314000;Bonn;Bonn Hbf;;;;;;295.142900;leastTime;100;10;100;10;100;0;;7.17;50.68;7.10;50.73;;de:05314:61101;
0                                                     NaN                                                                                       \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       06.03.2023 00:00:58;xxx.x.x.x;/vrrstd/;ID-B67508DC-4A34-4104-833B-35E6317C8CC7;0;dep;20230306;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;447.382400;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0                                                     NaN                                                                                                                                                                                                                      \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       07.03.2023 00:00:39;xxx.x.x.x;/vrrstd/;ID-1497CEAD-C142-4822-A220-4B3EF54C7BF9;0;dep;20230307;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;454.902300;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0                                                     NaN                                                                                                                                                                                                                      \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       08.03.2023 00:00:13;xx.xxx.xx.xxx;/nrwcibo-ios/;ID-23C8FA41-C419-4962-824A-D074DF587278;0;dep;20230308;1637;stop;itp;5515000;MÃ¼nster (Westf);Hauptbahnhof;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;411.114800;leastTime;100;10;100;10;100;0;;7.63;51.96;6.79;51.22;de:05515:41000;de:05111:18235;
0                                                     NaN                                                                                                                                                                                                                                               \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

       09.03.2023 00:00:13;xxx.x.x.x;/vrrstd/;ID-1AA045AB-3C75-4301-8B46-39932782458C;0;dep;20230309;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;417.838300;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0                                                     NaN                                                                                                                                                                                                                      \
1                                                     NaN
2                                                     NaN
3                                                     NaN
4                                                     NaN
...                                                   ...
729273                                                NaN
729274                                                NaN
729275                                                NaN
729276                                                NaN
729277                                                NaN

        ... Bonn.1 Von-Weichs-Str. 291.297200 100.3 7.07 50.73.1
0       ...    NaN             NaN        NaN   NaN  NaN     NaN  \
1       ...    NaN             NaN        NaN   NaN  NaN     NaN
2       ...    NaN             NaN        NaN   NaN  NaN     NaN
3       ...    NaN             NaN        NaN   NaN  NaN     NaN
4       ...    NaN             NaN        NaN   NaN  NaN     NaN
...     ...    ...             ...        ...   ...  ...     ...
729273  ...    NaN             NaN        NaN   NaN  NaN     NaN
729274  ...    NaN             NaN        NaN   NaN  NaN     NaN
729275  ...    NaN             NaN        NaN   NaN  NaN     NaN
729276  ...    NaN             NaN        NaN   NaN  NaN     NaN
729277  ...    NaN             NaN        NaN   NaN  NaN     NaN

        31.03.2023 00:00:24  ID-1C38976E-9720-4732-BE02-BD4921974B57
0                       NaN                                      NaN  \
1                       NaN                                      NaN
2                       NaN                                      NaN
3                       NaN                                      NaN
4                       NaN                                      NaN
...                     ...                                      ...
729273  31.03.2023 23:56:30  ID-C83BA9A7-48C4-4215-85F3-8E6722FF7593
729274  31.03.2023 23:56:58  ID-6CE36453-599F-4415-91D8-F00FA5669C95
729275  31.03.2023 23:57:57  ID-CBAAD830-3CDC-49E0-80B1-16393185CD9B
729276  31.03.2023 23:58:00  ID-6661CCB5-EDFE-482D-A725-59D80F38C56F
729277  31.03.2023 23:59:02  ID-39F5E2ED-7450-418F-AADE-98FA498ECB0E

          20230331 659.981000
0              NaN        NaN
1              NaN        NaN
2              NaN        NaN
3              NaN        NaN
4              NaN        NaN
...            ...        ...
729273  20230401.0   249.1798
729274  20230331.0   329.3395
729275  20230331.0   335.0535
729276  20230331.0   329.1617
729277  20230331.0   329.1763

[729278 rows x 295 columns]>

In [55]:
# Die gesamte Tabelle anzeigen
print(gesamt_tabelle.iloc[:15,[30]])

   27.03.2023 00:01:00;xxx.x.x.x;/vrrstd/;ID-1CC55A54-BA53-463D-9A30-2F1788EDBAB4;0;dep;20230327;0;stop;itp;5513000;Gelsenkirchen;Hbf;stop;itp;5111000;DÃ¼sseldorf;Hbf;;;;;;644.496700;leastTime;100;10;100;10;100;0;;7.10;51.50;6.79;51.22;de:05513:5613;de:05111:18235;
0                                                 NaN
1                                                 NaN
2                                                 NaN
3                                                 NaN
4                                                 NaN
5                                                 NaN
6                                                 NaN
7                                                 NaN
8                                                 NaN
9                                                 NaN
10                                                NaN
11                                                NaN
12                                                NaN
13                                                NaN
14                                                NaN